version: '3.5'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: test
    volumes:
      -
        type: bind
        source: /tmp/postgres-data
        target: /var/lib/postgresql/data

  bot:
    image: lostbot
    environment:
      CREATE_TABLE: 'yes'
      DB_SWITCH: 'on'
      TOKEN: '1149814876:AAH4COgEK8ZXkd2h4EKV5XVNkeMtIk0t7uw'
      HOST: db
      PORT: 5432
      USER: postgres
      PASSWORD: test
      DBNAME: postgres
      SSLMODE: disable
